### ISSUE TITLE
[S1 - PBI2] melihat fitur serta layanan yang tersedia.

### ISSUE THREAD

**Issue by amalsyah0301** [amalsyah0301/SI4406-KEL5#7]

**Comment by bliwisnu** [comment]
Proses fitur ini dapat dilihat pada gambar class diagram dibawah ini


![Image](https://user-images.githubusercontent.com/115610830/226273214-51d63207-c4e9-4a75-a77c-7761316814a5.png)



![Image](https://user-images.githubusercontent.com/115610830/226273438-4faafc92-ca04-41e1-b686-96825fb3a674.png)
